<a href="https://colab.research.google.com/github/VyAndra31/3-Livyandra/blob/main/tugas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TUGAS NUMPY 2026** 🧮

---
**Nama:** Livyandra Lita Halim

**NIM:** 255150200111009  

Notebook ini berisi penugasan **NumPy** sebagai latihan lanjutan setelah workshop.

### Aturan singkat
- Kerjakan mandiri.
- Gunakan **NumPy** sebagai alat utama.
- Untuk soal yang berkaitan dengan masking, broadcasting, dan reshaping, usahakan **tidak menggunakan loop** jika memang bisa diselesaikan dengan operasi NumPy.
- Tulis jawaban langsung di cell yang sudah disediakan.


## **📦 Import Library**

Jalankan cell berikut terlebih dahulu.


In [ ]:
import numpy as np

# Seed supaya hasil random konsisten
rng = np.random.default_rng(42)


## **📌 Soal 1: Membuat Array & Membaca Informasinya**

Buatlah array NumPy bernama `scores` dengan isi nilai berikut:

`[78, 85, 90, 66, 74, 88, 92, 81]`

Lalu tampilkan:
1. Isi array
2. Jumlah dimensi
3. Shape
4. Banyak elemen
5. Tipe data

**Hint:** gunakan `np.array`, lalu cek `ndim`, `shape`, `size`, dan `dtype`.


In [ ]:
# Tulis jawabanmu di sini
scores = np.array([78, 85, 90, 66, 74, 88, 92, 81])


In [ ]:
# isi array
print(scores)

[78 85 90 66 74 88 92 81]


In [ ]:
# jumlah dimensi
scores.ndim

1

In [ ]:
# shape
scores.shape

(8,)

In [ ]:
# banyak elemen
scores.size

8

In [ ]:
# tipe data
scores.dtype

dtype('int64')

## **📌 Soal 2: Factory Functions**

Gunakan fungsi bawaan NumPy untuk membuat:
1. Array `A` berukuran `3x4` yang seluruh elemennya `0`
2. Array `B` berukuran `2x3` yang seluruh elemennya `1`
3. Array `C` berukuran `3x3` yang seluruh elemennya `7`
4. Matriks identitas `D` berukuran `4x4`
5. Array `E` yang berisi 6 angka dari `0` sampai `1` dengan jarak sama rata

Tampilkan semua hasilnya.


In [ ]:
# Tulis jawabanmu di sini
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

## **📌 Soal 3: Indexing & Slicing**

Perhatikan array berikut:


In [ ]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Dari array tersebut, tampilkan:
1. Elemen pada baris ke-2 kolom ke-3
2. Seluruh baris pertama
3. Seluruh kolom terakhir
4. Subarray 2x2 di tengah
5. Array hasil membalik urutan kolom pada semua baris

**Catatan:** gunakan indexing/slicing NumPy.


In [ ]:
# elemen pada baris ke 2 kolom ke 3
arr[1,2]


np.int64(7)

In [ ]:
# seluruh baris pertama
arr[0]

array([1, 2, 3, 4])

In [ ]:
# seluruh kolom terakhir
arr[:, 3]

array([ 4,  8, 12, 16])

In [ ]:
# subarray 2x2 di tengah
arr[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
# array hasil membalik urutan kolom pada semua baris
arr[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

## **📌 Soal 4: Boolean Masking & `np.where()`**

Diberikan array suhu berikut:


In [ ]:
temps = np.array([29, 31, 35, 28, 33, 27, 30, 36, 32, 26])
print(temps)


[29 31 35 28 33 27 30 36 32 26]


Kerjakan hal berikut:
1. Ambil semua suhu yang **lebih dari 30**
2. Hitung berapa banyak suhu yang **lebih dari atau sama dengan 32**
3. Buat array label baru bernama `status` dengan aturan:
   - `"panas"` jika suhu > 32
   - `"normal"` jika suhu 29 s.d. 32
   - `"dingin"` jika suhu < 29

**Hint:** untuk poin (3), kamu bisa menggunakan `np.where()` bertingkat.


In [ ]:
# suhu lebih dari 30
temps[temps > 30]

array([31, 35, 33, 36, 32])

In [ ]:
# banyak suhu lebih dari sama dengan 32
np.sum(temps >= 32)

np.int64(4)

In [ ]:
# array label baru bernama status
status = np.where(temps > 32, 'panas', np.where(temps >= 29, 'normal', 'dingin'))
print(status)

['normal' 'normal' 'panas' 'dingin' 'panas' 'dingin' 'normal' 'panas'
 'normal' 'dingin']


## **📌 Soal 5: View vs Copy**

Buat array berikut:


In [ ]:
x = np.array([10, 20, 30, 40, 50, 60])
print(x)


[10 20 30 40 50 60]


Lalu lakukan:
1. Buat `view_part` dari elemen indeks 1 sampai 4 menggunakan slicing
2. Buat `copy_part` dari elemen indeks `[1, 2, 3, 4]` menggunakan advanced indexing
3. Ubah elemen pertama `view_part` menjadi `999`
4. Ubah elemen pertama `copy_part` menjadi `-100`
5. Tampilkan `x`, `view_part`, dan `copy_part`

Terakhir, tuliskan dengan singkat:
- mana yang menyebabkan array asli berubah?
- mana yang tidak?


In [ ]:
# Tulis jawabanmu di sini
view_part = x[1:5]
copy_part = x[[1,2,3,4]]
view_part[0] = 999
copy_part[0] = -100
print(x)
print(view_part)
print(copy_part)

# Tambahkan penjelasan singkat dalam komentar juga.
# nah kalau view_part ini dia pake basic indexing dimana dia cuma nyalin reference nya gitu
# makanya dia tetep keubah tuh x nya yang index ke 1 nya juga ikutan jadi 999
# kalau copy_part dia advance indexing dimana dia langsung copy dan bikin array baru
# jadi ga akan ngaruh ke array x nya


[ 10 999  30  40  50  60]
[999  30  40  50]
[-100   30   40   50]


## **📌 Soal 6: Statistik Dasar & Missing Value (`NaN`)**

Gunakan array berikut:


In [ ]:
values = np.array([12, 15, np.nan, 18, 21, np.nan, 24, 30])
print(values)


[12. 15. nan 18. 21. nan 24. 30.]


Tampilkan:
1. Rata-rata biasa dengan `np.mean()`
2. Rata-rata yang mengabaikan `NaN` dengan `np.nanmean()`
3. Standar deviasi yang mengabaikan `NaN` dengan `np.nanstd()`
4. Nilai minimum dan maksimum yang mengabaikan `NaN`

Lalu jelaskan singkat kenapa hasil `np.mean()` bisa berbeda dari `np.nanmean()`.


In [ ]:
# rata rata biasa
np.mean(values)


np.float64(nan)

In [ ]:
# rata rata yang mengabaikan NaN
np.nanmean(values)

np.float64(20.0)

In [ ]:
# standar deviasi yang mengabaikan NaN
np.nanstd(values)

np.float64(5.916079783099616)

In [ ]:
# nilai minimum dan maximum yang mengabaikan NaN
print(np.nanmin(values))
print(np.nanmax(values))

12.0
30.0


In [ ]:
# kalau np.mean() biasa, dia menghitung rata rata dari semua nilai yang ada dalam array
# kalau ada NaN nya, maka hasilnya akan menjadi NaN karena nilai NaN nya juga ikut kehitung
# kalau np.nanmean() dia mengabaikan data NaN jadi yang dihitung hanya rata rata dari data yang valid saja


## **📌 Soal 7: Broadcasting untuk Normalisasi**

Diberikan matriks fitur berikut:


In [ ]:
X = np.array([
    [170, 65, 28],
    [165, 55, 24],
    [180, 75, 30],
    [175, 70, 29]
], dtype=float)

print(X)


[[170.  65.  28.]
 [165.  55.  24.]
 [180.  75.  30.]
 [175.  70.  29.]]


Anggap setiap kolom merepresentasikan fitur yang berbeda.  
Lakukan normalisasi z-score sederhana dengan rumus:

$$
Z = \frac{X - \text{mean kolom}}{\text{std kolom}}
$$

Tampilkan:
1. Mean per kolom
2. Std per kolom
3. Hasil normalisasi `Z`

**Hint:** gunakan `axis=0` dan manfaatkan broadcasting NumPy.


In [ ]:
# mean per kolom
np.mean(X, axis=0)


array([172.5 ,  66.25,  27.75])

In [ ]:
# standar deviasi per kolom
np.std(X, axis=0)

array([5.59016994, 7.39509973, 2.27760839])

In [ ]:
# hasil normalisasi Z
z = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
print(z)

[[-0.4472136  -0.16903085  0.10976426]
 [-1.34164079 -1.52127766 -1.6464639 ]
 [ 1.34164079  1.18321596  0.98787834]
 [ 0.4472136   0.50709255  0.5488213 ]]


## **📌 Soal 8: Reshape & Mini Challenge**

Gunakan array 1 dimensi berikut:


In [ ]:
z = np.arange(1, 25)
print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Kerjakan hal berikut:
1. Ubah `z` menjadi matriks berukuran `6x4`
2. Ubah hasilnya menjadi bentuk `3x2x4`
3. Ambil kembali seluruh data tersebut menjadi array 1 dimensi
4. Bonus: buat array window 4 elemen yang bergeser dari `z`, sehingga bentuk akhirnya menjadi:

`[[1,2,3,4], [2,3,4,5], ..., [21,22,23,24]]`

**Hint bonus:** boleh gunakan loop **atau** `sliding_window_view` jika kamu sudah tahu.


In [ ]:
# ubah z menjadi matriks 6x4
z_6x4 = z.reshape(6,4)
print(z_6x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
# ubah hasilnya jadi bentuk 3x2x4
z_3x2x4 = z_6x4.reshape(3,2,4)
print(z_3x2x4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# buat lagi jadi array 1 dimensi
print(z_3x2x4.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
# buat array window 4 elemen yang bergeser dari z
from numpy.lib.stride_tricks import sliding_window_view
windows = sliding_window_view(z, 4)
print(windows)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]]


# **🎯 Penutup**

Kalau kamu sudah menyelesaikan semua soal:
- cek lagi hasil outputmu,
- pastikan bentuk array dan logikanya sesuai,
- lalu simpan notebook ini sebelum dikumpulkan.

Semangat! 🚀
